# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2019-12-26 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_info',
            field=models.TextField(),
        ),
    ]
